---
name: CI

on:
  workflow_run:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  lint-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: custom wkflow
        uses: ./.github/actions/custom-action
        with:
          custom-input: test
      
      - name: inject
        run: |
            echo "This is not vulnerable"
